#!/usr/bin/env bash

# Copyright (C) 2013 Preferred Infrastructure and Nippon Telegraph and Telephone Corporation.

RUBY="ruby"

function r() {
	echo "$@"
	"$@"
}

function preprocess() {
	file="$1"
	out="$(dirname "$file")/$(basename "$file" mpl)"
	r "$RUBY" -I. mplex -rmpl "$file" -o "$out"
	if [ "$?" != 0 ]; then
		echo ""
		echo "** preprocess failed **"
		echo ""
		exit 1
	fi
}

preprocess jubatus/mp/object_callback.hmpl
preprocess jubatus/mp/sparse_array.hmpl
preprocess jubatus/mp/sync.hmpl
preprocess jubatus/mp/wavy.hmpl

